[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_dao = "82FjXcf9un78RSGZFVGyNGaHHqksuz6BMdGtgo3xSYBP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/baron/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
